install.packages( "thinkr" )
install.packages( "shiny" )
install.packages( "leaflet" )
install.packages( "sf" )
install.packages( "dplyr" )
install.packages( "rnaturalearth" )
install.packages( "rnaturalearthdata" )
install.packages( "golem" )